"""
通用模块 - 常量、模型、工具函数和异常定义
"""
from .constants import (
    GameCommands,
    GameModes,
    TimePhases,
    TimeThresholds,
    FatigueLevel,
    FatigueMultipliers,
    SanityThresholds,
    HealthThresholds,
    EntropyThresholds,
    PerceptionLevels,
    ActionKeywords,
    ConfigDefaults,
    DirectoryNames,
    FileNames,
    ErrorMessages,
    SuccessMessages,
    TimeDescriptions,
    EntropyDescriptions,
    TimePressureLevels,
)

from .models import (
    ActionRecord,
    PhysicalStatus,
    MentalStatus,
    PsychologicalPressure,
    ItemDetails,
    ActionResult,
    TimeInfo,
    EnvironmentChange,
    PlayerIdentity,
    RuleInfo,
    GameContext,
    JsonPrimitive,
    JsonValue,
    JsonObject,
    PlayerStatusDict,
    RuleDict,
    StateUpdatesDict,
    GameContextDict,
    InteractionRecordDict,
    LocationRecordDict,
    ActionRecordDict,
    SoundInfoDict,
    PlayerDataDict,
    GameStateDict,
    BehaviorResultDict,
    AttitudeCheckResultDict,
    AttitudeContradictionDict,
    LastSeenInfoDict,
)


from .utils import (
    is_dir_writable,
    resolve_data_dir,
    safe_get_dict_value,
    normalize_text_for_comparison,
    contains_action_keyword,
    validate_sanity_value,
    validate_health_value,
)

from .exceptions import (
    RuleHorrorError,
    ConfigError,
    ConfigLoadError,
    ConfigValidationError,
    GameStateError,
    GameNotFoundError,
    GameAlreadyExistsError,
    PlayerError,
    PlayerNotFoundError,
    PlayerAlreadyJoinedError,
    PlayerNotInGameError,
    SaveError,
    SaveNotFoundError,
    SaveLoadError,
    SaveWriteError,
    LLMError,
    LLMRequestError,
    LLMResponseError,
    LLMTimeoutError,
    ImageGenerationError,
    ValidationError,
    InvalidActionError,
    InvalidCommandError,
)

__all__ = [
    # 常量
    "GameCommands",
    "GameModes",
    "TimePhases",
    "TimeThresholds",
    "FatigueLevel",
    "FatigueMultipliers",
    "SanityThresholds",
    "HealthThresholds",
    "EntropyThresholds",
    "PerceptionLevels",
    "ActionKeywords",
    "ConfigDefaults",
    "DirectoryNames",
    "FileNames",
    "ErrorMessages",
    "SuccessMessages",
    "TimeDescriptions",
    "EntropyDescriptions",
    "TimePressureLevels",
    # 模型
    "ActionRecord",
    "PhysicalStatus",
    "MentalStatus",
    "PsychologicalPressure",
    "ItemDetails",
    "ActionResult",
    "TimeInfo",
    "EnvironmentChange",
    "PlayerIdentity",
    "RuleInfo",
    "GameContext",
    # JSON 类型
    "JsonPrimitive",
    "JsonValue",
    "JsonObject",
    # TypedDict 类型
    "PlayerStatusDict",
    "RuleDict",
    "StateUpdatesDict",
    "GameContextDict",
    "InteractionRecordDict",
    "LocationRecordDict",
    "ActionRecordDict",
    "SoundInfoDict",
    "PlayerDataDict",
    "GameStateDict",
    "BehaviorResultDict",
    "AttitudeCheckResultDict",
    "AttitudeContradictionDict",
    "LastSeenInfoDict",

    # 工具函数
    "is_dir_writable",
    "resolve_data_dir",
    "safe_get_dict_value",
    "normalize_text_for_comparison",
    "contains_action_keyword",
    "validate_sanity_value",
    "validate_health_value",
    # 异常
    "RuleHorrorError",
    "ConfigError",
    "ConfigLoadError",
    "ConfigValidationError",
    "GameStateError",
    "GameNotFoundError",
    "GameAlreadyExistsError",
    "PlayerError",
    "PlayerNotFoundError",
    "PlayerAlreadyJoinedError",
    "PlayerNotInGameError",
    "SaveError",
    "SaveNotFoundError",
    "SaveLoadError",
    "SaveWriteError",
    "LLMError",
    "LLMRequestError",
    "LLMResponseError",
    "LLMTimeoutError",
    "ImageGenerationError",
    "ValidationError",
    "InvalidActionError",
    "InvalidCommandError",
]
